#pragma once

enum ObjectNames
{
	UNKNOWN,
	RENDER_SYSTEM,
	MOVEMENT_SYSTEM,
	ANIMATION_SYSTEM,
	ANIMATION_COMPONENT,
	RIGID_BODY_COMPONENT,
	SPRITE_COMPONENT,
	TRANSFORM_COMPONENT,
	TILE_ENTITY,
	CHOPER_ENTITY,
	TRUCK_ENTITY,
	TANK_ENTITY
};